## OR gate using Neural Nets

### 1. Dataset generation

In [1]:
import numpy as np

In [2]:
x_data1 = np.array([[1.0, 1.0, 1.0, 1.0], [0.0, 0.0, 1.0, 1.0], [0.0, 1.0, 0.0, 1.0]])

In [3]:
x_data1

array([[1., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 1., 0., 1.]])

In [4]:
y_data1 = np.array([0.0, 1.0, 1.0, 1.0])

In [5]:
x_data1.T

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [6]:
x_data1 = x_data1.T

In [7]:
x_data1

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [8]:
x_data1.shape

(4, 3)

In [9]:
#shape of the data
m = x_data1.shape[0]
n = x_data1.shape[1]

In [10]:
#theta initialization
Theta = np.zeros(shape = (n,))

In [11]:
Theta

array([0., 0., 0.])

### 2.1 Feed-forward

In [12]:
x_data1.shape

(4, 3)

In [13]:
Theta.shape

(3,)

In [14]:
def sigmoid(a1, theta):
    z = a1 @ theta
    h = 1/(1 + np.exp(-z))
    return h

    Hypothesis before training:

In [15]:
h_before = sigmoid(x_data1, Theta)

### 2.2 Training

In [16]:
#Cost function
def cost(h, y):
    """
    h.shape = (m,)
    y.shape = (m,)
    """
    cost = (-1/m) * (y.T @ np.log(h) + np.dot((1 - y).T, np.log(1 - h)))
    return cost

In [17]:
cost(h_before, y_data1)

0.6931471805599453

#### 2.2.1 Gradient Descent implementation

In [55]:
#theta initialization
Theta = np.zeros(shape = (n,))

In [56]:
Theta

array([0., 0., 0.])

In [57]:
alpha = 0.01

In [58]:
(sigmoid(x_data1, Theta) - y_data1).T @ x_data1

array([-1., -1., -1.])

In [59]:
#Gradient Descent
for i in range(3000):
    Theta = Theta - alpha/m * ((sigmoid(x_data1, Theta) - y_data1).T @ x_data1 )

In [60]:
Theta

array([-0.33313687,  2.11923516,  2.11923516])

### 2.3 Results

In [61]:
h_after = sigmoid(x_data1, Theta)

In [62]:
h_after

array([0.41747757, 0.85644825, 0.85644825, 0.98026315])

In [63]:
h_results = (h_after >= 0.5)

In [64]:
y_results = (y_data1 >= 0.5)

In [65]:
#Accuracy
np.mean(h_results == y_results) * 100

100.0